# Question
Look at this function:

```js
const bailOut = () => {
  for (let i = 0; i < 5; i++) {
    if (i > 3) return;
    console.log('Inside the loop', i);
  }
  console.log('Outside the loop');
};
```

Is that `console.log('Outside the loop');` ever going to run? Why or why not?

# Answer

The `console.log('Outside the loop');` won't run because the for loop is already returning inside the for loop scope so when invoking `bailOut`, the function reads down the code till it hits the return value. 

# Teacher Feedback
